### ISSUE TITLE
Use custom Podlive notification sound when a livestream starts

### ISSUE THREAD

**Issue by funkenstrahlen** [phranck/podlive-macos#8]
Currently Podlive does play the macOS default notification sound. However on iOS there will be a custom notification sound for Podlive starting with the release of Podlive 3.0. The backend server already supports the new notification sound now. The notifications contains `quite-impressed.caf` as a key for the sound file.

**Comment by phranck** [comment]
@funkenstrahlen Can you please attach the sound file to this issue, so we can use the same on both platforms. Thanks! (-:

**Comment by funkenstrahlen** [comment]
I can not upload audio files to Github issues. This is the source: https://notificationsounds.com/notification-sounds/quite-impressed-565

Has to be converted to `.caf`. Apple does have a documentation on how to do that with `avconvert`.

**Comment by phranck** [comment]
Really? You don't see this?
Thank's for the link btw. 😊

<img width="705" alt="screenshot 2018-03-15 at 20 48 59" src="https://user-images.githubusercontent.com/871198/37487643-726a43b8-2892-11e8-84d5-e39f5109ef48.png">

**Comment by funkenstrahlen** [comment]
Of course I see that. However audio file types are not allowed.

**Comment by phranck** [comment]
When I read the code for `PFPush` correctly there is nothing to do but adding this sound file to the project, and everything should work?

**Comment by funkenstrahlen** [comment]
> When I read the code for PFPush correctly there is nothing to do but adding this sound file to the project, and everything should work?

Yes!

**Comment by phranck** [comment]
Cool. Then I'm done. (-:

**Comment by phranck** [comment]
Doesn't seems to work as expected. Needs investigation.

**Comment by phranck** [comment]
I will close this issue. After some more investigations I can conclude that a custom notification sound isn't possible for macOS.
